#! /bin/bash

#############################
# 1. Install
#############################

#apt-get update
#apt-get install git-core
#apt-get install openjdk-6-jdk openjdk-6-source openjdk-6-jre-headless openjdk-6-jre-lib 
#apt-get install ant
#apt-get install build-essential

#mkdir jetty
#cd jetty
#wget http://download.eclipse.org/jetty/stable-8/dist/jetty-distribution-8.1.5.v20120716.zip
#unzip jetty-distribution-8.1.5.v20120716.zip

#mkdir flex
#cd flex
#wget https://dl.dropbox.com/u/67910030/flex_sdk_4.1.0.16076A.zip
#unzip flex_sdk_4.1.0.16076A.zip

#using a proxy?
#git config --global http.proxy proxy.whu.edu:3128
#git clone https://github.com/trobar/gte.git

#############################
# 2. Update
#############################

cd ~/gte
git checkout -f master
git pull

cp ~/build.properties build.properties

#############################
# 3. Stop Server
#############################

cd ~/gte

ant jetty-stop

#############################
# 4. Build
############################

cd ~/gte

ant makeProductive
ant makeWarFile
ant makeZipFile

#############################
# 5. Start Server
#############################

cd ~/gte

ant jetty-start

