/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class lse_math_games_web_AlgoInterface */

#ifndef _Included_lse_math_games_web_AlgoInterface
#define _Included_lse_math_games_web_AlgoInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lse_math_games_web_AlgoInterface
 * Method:    callnative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lse_math_games_web_AlgoInterface_callnative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
